# Generated by Django 3.0.2 on 2020-01-08 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('author', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Review'),
        ),
    ]
