# Generated by Django 3.0.2 on 2020-01-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20200108_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.Review'),
        ),
    ]
