# Generated by Django 3.0.2 on 2020-01-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20200108_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='review',
        ),
        migrations.AddField(
            model_name='food',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resources.Food'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
