# Generated by Django 3.0.2 on 2020-01-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20200108_1011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Restaurant',
        ),
    ]
