# Generated by Django 3.0.2 on 2020-01-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
