# Generated by Django 3.0.2 on 2020-01-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20200112_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.IntegerField(),
        ),
    ]
