# Generated by Django 3.0.2 on 2020-01-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_product_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
